"""G1.5: suppression, prospects, qa_samples tables

Revision ID: 08e29df9a3e2
Revises: 99655fdbe283
Create Date: 2026-09-16 15:37:45.183929

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '08e29df9a3e2'
down_revision: Union[str, None] = '99655fdbe283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prospects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('ein', sa.String(length=9), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_trigger', sa.String(length=50), nullable=True),
    sa.Column('trigger_angle', sa.String(length=255), nullable=True),
    sa.Column('trigger_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gap_rank', sa.Numeric(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'ein', name='uq_prospects_client_ein')
    )
    op.create_index(op.f('ix_prospects_ein'), 'prospects', ['ein'], unique=False)
    op.create_table('qa_samples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('ein', sa.String(length=9), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('citation', sa.Text(), nullable=True),
    sa.Column('verdict', sa.String(length=20), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_samples_ein'), 'qa_samples', ['ein'], unique=False)
    op.create_table('suppression',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('ein', sa.String(length=9), nullable=True),
    sa.Column('org_name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('partner_window_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suppression')
    op.drop_index(op.f('ix_qa_samples_ein'), table_name='qa_samples')
    op.drop_table('qa_samples')
    op.drop_index(op.f('ix_prospects_ein'), table_name='prospects')
    op.drop_table('prospects')
    # ### end Alembic commands ###
