"""initial schema: organizations, filings, runs

Revision ID: 102f11dd6616
Revises: 
Create Date: 2026-09-15 23:18:57.051314

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '102f11dd6616'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ein', sa.String(length=9), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('form_type', sa.String(length=10), nullable=False),
    sa.Column('object_id', sa.String(length=30), nullable=False),
    sa.Column('xml_object_url', sa.String(length=500), nullable=True),
    sa.Column('revenue_total', sa.Numeric(), nullable=True),
    sa.Column('contributions', sa.Numeric(), nullable=True),
    sa.Column('program_revenue', sa.Numeric(), nullable=True),
    sa.Column('govt_grants', sa.Numeric(), nullable=True),
    sa.Column('fundraising_expense', sa.Numeric(), nullable=True),
    sa.Column('officers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ein', 'object_id', name='uq_filings_ein_object_id')
    )
    op.create_index(op.f('ix_filings_ein'), 'filings', ['ein'], unique=False)
    op.create_table('organizations',
    sa.Column('ein', sa.String(length=9), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('ntee', sa.String(length=10), nullable=True),
    sa.Column('ruling_year', sa.Integer(), nullable=True),
    sa.Column('revenue_latest', sa.Numeric(), nullable=True),
    sa.Column('foundation_code', sa.String(length=2), nullable=True),
    sa.Column('bmf_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('ein')
    )
    op.create_table('runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('counts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('runs')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_filings_ein'), table_name='filings')
    op.drop_table('filings')
    # ### end Alembic commands ###
