"""G1.4: scores table; mission/program text and website extraction

Revision ID: 99655fdbe283
Revises: 1cded851bc4e
Create Date: 2026-09-16 13:20:17.404027

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '99655fdbe283'
down_revision: Union[str, None] = '1cded851bc4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('ein', sa.String(length=9), nullable=False),
    sa.Column('icp_version', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=10), nullable=False),
    sa.Column('values_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('alignment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('capacity', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gap_rank', sa.Numeric(), nullable=True),
    sa.Column('disqualified', sa.Boolean(), nullable=False),
    sa.Column('dq_reason', sa.Text(), nullable=True),
    sa.Column('soft_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'ein', 'icp_version', 'stage', name='uq_scores_client_ein_version_stage')
    )
    op.create_index(op.f('ix_scores_ein'), 'scores', ['ein'], unique=False)
    op.add_column('filings', sa.Column('mission_text', sa.Text(), nullable=True))
    op.add_column('filings', sa.Column('program_text', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('filings', sa.Column('significant_change_ind', sa.Boolean(), nullable=True))
    op.add_column('organizations', sa.Column('website', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'website')
    op.drop_column('filings', 'significant_change_ind')
    op.drop_column('filings', 'program_text')
    op.drop_column('filings', 'mission_text')
    op.drop_index(op.f('ix_scores_ein'), table_name='scores')
    op.drop_table('scores')
    # ### end Alembic commands ###
